[package]
name = "xpx-sdk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
crate-type = ["lib", "staticlib", "cdylib"]

[dependencies]
serde_json = "1"
serde = "1"

[lib]
name = "sdk"
path = "src/lib.rs"
